### ISSUE TITLE
Due Date

### ISSUE THREAD

**Issue by fischest** [iansinnott/things-2do-importer#2]
Hello,

great work. Found a way to set the due date via Apple Script. Not delivering a pull request as I am working on a project to utilize the JSON api of Things now. Still no chance to set repeats though ;-(.

But to set the due date, you could use:

set duedate to current date
	tell duedate to set its year to (text 7 thru 8 of duedateStr)
	tell duedate to set its month to (text 4 thru 5 of duedateStr)
	tell duedate to set its day to (text 1 thru 2 of duedateStr)
	

    set newTask to make new to do with properties {name: task_name} at beginning of project project_name
    set notes of newTask to task_notes
	set due date of newTask to duedate - 2 * days

No idea why it always has to be set to date -2.

**Comment by iansinnott** [comment]
Cheers, thanks for the note. 

Yup, these days I suspect the JSON API is much more usable, or at least familiar.
